version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3001:3001"
